#######################################

#Registry Db connection
REGDBNAME = "PyOllivHotelRegistration"
REGHOST="localhost"
REGUSER="root"
REGPASSWORD="pyolliv"
REGPORT="3306"
REGDBTYPE="mariadb"


#Admin Db connection
ADMDBNAME = "adminflow"
ADMHOST="localhost"
ADMUSER="root"
ADMPASSWORD="pyolliv"
ADMPORT="3306"
ADMDBTYPE="mariadb"
