Religion = "Religion"
Gender = "Gender"
MartialStatus = "MartialStatus"
height = "height"
Disablity = "Disablity"
HealthInformation = "HealthInformation"
BloodGroup = "BloodGroup"
Languages = "Languages"
caste = "caste"
country = "country"
State = "State"
Diet = "Diet"
salaryRange = "salaryRange"
AnnualIncome = "AnnualIncome"
community = "community"
workingin = "workingin"
Proffession = "Proffession"
qualifications = "qualifications"
subcommunity = "subcommunity"
Gothram = "Gothram"
City = "City" 
